<?php



/**
 * This class defines the structure of the 'sf_tagging' table.
 *
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue Jan 25 18:31:06 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.plugins.sfPropel15TaggableBehaviorPlugin.lib.model.map
 */
class SfTaggingTableMap extends TableMap
{

  /**
   * The (dot-path) name of this class
   */
  const CLASS_NAME = 'plugins.sfPropel15TaggableBehaviorPlugin.lib.model.map.SfTaggingTableMap';

  /**
   * Initialize the table attributes, columns and validators
   * Relations are not initialized by this method since they are lazy loaded
   *
   * @return     void
   * @throws     PropelException
   */
  public function initialize()
  {
    // attributes
    $this->setName('sf_tagging');
    $this->setPhpName('SfTagging');
    $this->setClassname('SfTagging');
    $this->setPackage('plugins.sfPropel15TaggableBehaviorPlugin.lib.model');
    $this->setUseIdGenerator(true);
    // columns
    $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
    $this->addForeignKey('TAG_ID', 'TagId', 'INTEGER', 'sf_tag', 'ID', false, null, null);
    $this->addColumn('TAGGABLE_MODEL', 'TaggableModel', 'VARCHAR', false, 30, null);
    $this->addColumn('TAGGABLE_ID', 'TaggableId', 'INTEGER', false, null, null);
    $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
    $this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
    // validators
  }

  /**
   * Build the RelationMap objects for this table relationships
   */
  public function buildRelations()
  {
    $this->addRelation('SfTag', 'SfTag', RelationMap::MANY_TO_ONE, array('tag_id' => 'id', ), null, null);
  }

  /**
   * 
   * Gets the list of behaviors registered for this table
   * 
   * @return array Associative array (name => parameters) of behaviors
   */
  public function getBehaviors()
  {
    return array(
      'timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
      'symfony' => array('form' => 'true', 'filter' => 'true', ),
      'symfony_behaviors' => array(),
      'alternative_coding_standards' => array('brackets_newline' => 'true', 'remove_closing_comments' => 'true', 'use_whitespace' => 'true', 'tab_size' => '2', 'strip_comments' => 'false', ),
    );
  }

}
