<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_tagging' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue Jan 25 14:58:49 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPropel15TaggableBehaviorPlugin.lib.model
 */
class SfTaggingPeer extends BaseSfTaggingPeer
{

}
