<?php



/**
 * Skeleton subclass for representing a row from the 'taggable_tags' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Tue Feb  1 10:40:06 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPropel15TaggableBehaviorPlugin.lib.model
 */
class TaggableTags extends BaseTaggableTags {

} // TaggableTags
